# Generated by Django 5.2.7 on 2025-12-28 14:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id_brand', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=50)),
                ('tara_origine', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=100)),
                ('an_infiintare', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=50)),
                ('descriere', models.TextField()),
                ('numar_produse', models.IntegerField()),
                ('culoare', models.CharField(blank=True, help_text='ex: #4f46e5', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='ex: fa-dumbbell', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Culoare',
            fields=[
                ('id_culoare', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=50)),
                ('cod_hex', models.CharField(max_length=7)),
                ('data_adaugare', models.DateField()),
                ('intensitate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dimensiune',
            fields=[
                ('id_dimensiune', models.AutoField(primary_key=True, serialize=False)),
                ('eticheta', models.CharField(max_length=20)),
                ('unitate_masura', models.CharField(max_length=10)),
                ('disponibil', models.BooleanField()),
                ('lungime', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('latime', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Furnizor',
            fields=[
                ('id_furnizor', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=50)),
                ('tara', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=20)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Locatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa', models.CharField(max_length=255)),
                ('oras', models.CharField(max_length=100)),
                ('judet', models.CharField(max_length=100)),
                ('cod_postal', models.CharField(max_length=10)),
                ('nr', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Organizator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('county', models.CharField(blank=True, max_length=50)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('newsletter', models.BooleanField(default=False)),
                ('cod', models.CharField(blank=True, help_text='Cod de confirmare email.', max_length=100, null=True)),
                ('email_confirmat', models.BooleanField(default=False, help_text='Daca emailul a fost confirmat')),
                ('blocat', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [('vizualizeaza_oferta', 'Poate vizualiza oferta speciala')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id_produs', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=100)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descriere', models.TextField()),
                ('stoc_disponibil', models.BooleanField()),
                ('stoc', models.PositiveIntegerField(default=0)),
                ('data_adaugare', models.DateField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie.brand')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie.categorie')),
                ('culori', models.ManyToManyField(to='aplicatie.culoare')),
                ('dimensiuni', models.ManyToManyField(to='aplicatie.dimensiune')),
                ('furnizor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie.furnizor')),
            ],
        ),
        migrations.CreateModel(
            name='Promotie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('subiect', models.CharField(max_length=150)),
                ('mesaj_baza', models.TextField()),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
                ('data_expirare', models.DateTimeField()),
                ('procent_discount', models.PositiveIntegerField(default=10, help_text='Reducere procentuală (ex: 10 pentru 10%).')),
                ('activ', models.BooleanField(default=True)),
                ('categorii', models.ManyToManyField(related_name='promotii', to='aplicatie.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Vizualizare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vizualizare', models.DateTimeField(auto_now_add=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vizualizari', to='aplicatie.produs')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vizualizari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_vizualizare'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('min_order_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('eligible_users', models.ManyToManyField(blank=True, related_name='vouchere_eligibile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('noua', 'Nouă'), ('proc', 'În procesare'), ('ship', 'În livrare'), ('done', 'Finalizată'), ('cancel', 'Anulată')], default='noua', max_length=10)),
                ('metoda_plata', models.CharField(choices=[('card', 'Card'), ('ramburs', 'Ramburs'), ('transfer', 'Transfer bancar')], default='card', max_length=10)),
                ('adresa_livrare', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comenzi', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comenzi', to='aplicatie.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='ComandaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('pret_unitar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linii', to='aplicatie.comanda')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linii_comanda', to='aplicatie.produs')),
            ],
            options={
                'unique_together': {('comanda', 'produs')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('titlu', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewuri', to='aplicatie.produs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewuri', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'produs')},
            },
        ),
    ]
